export const FETCH_DATA_FAIL='FETCH_DATA_FAIL'
export const FETCH_DATA_SUCCESS="FETCH_DATA_SUCCESS"

export const FETCH_LATEST_ENTRY = 'SET_DATA'
export const FETCH_TODAYS_ENTRIES="FETCH_TODAYS_ENTRIES"